### ISSUE TITLE
1.16.5 Server crashes when upgraded magmatic golem attacks any monster

### ISSUE THREAD

**Issue by ChanLicher** [zKryle/JustEnoughGolems#9] opened 2022-04-24 07:47 UTC
**Describe the bug**
The server crashes immediately when my upgraded magmatic golem attacks any monster.

**To Reproduce**
It happens every time when it attacks something.

**Expected behavior**
For the server not to crash.

**Screenshots**
No screenshots available.

**Version:**
- Mohist-1.16.5-965-server (I don't know forge version but it should be updated to newest automatically)

**Additional context**
[crash-2022-04-24_14.46.54-server.txt](https://github.com/zKryle/JustEnoughGolems/files/8549220/crash-2022-04-24_14.46.54-server.txt)

**Comment by zKryle** [comment] 2022-04-24 07:51
Hello! Thanks for your report, does this happen on the latest version of the mod? 

I'll try to reproduce this.
-zKryle

**Comment by ChanLicher** [comment] 2022-04-24 08:16
I am using "JustEnoughGolems Magma Release (v2.2) 1.16.5". It should be the newest. I'm new at server management, and not sure whether it caused by other mods. I will test in single player mode.

**Comment by ChanLicher** [comment] 2022-04-24 09:01
> I am using "JustEnoughGolems Magma Release (v2.2) 1.16.5". It should be the newest. I'm new at server management, and not sure whether it caused by other mods. I will test in single player mode.

I test in single player mode, and it works fine. So it may caused by mohist server?

**Comment by zKryle** [comment] 2022-04-26 13:52
> 

I'll try to reproduce it hosting a server.

**Comment by padlocks** [comment] 2022-04-28 22:07
My server experiences the same crash. I also use the RoadRunner mod and disabling `mixin.ai` solves this, but it's not ideal since there is performance to be gained. I don't use Mohist either, just a forge server.

**Comment by zKryle** [comment] 2022-04-28 22:14
So this happens with mixins enabled?

**Comment by padlocks** [comment] 2022-04-28 22:20
> So this happens with mixins enabled?

Yes. Reading over the original crash log, we both use RoadRunner as well.

**Comment by zKryle** [comment] 2022-04-28 22:21
This might be an issue with the way RoadRunner modifies the game, I don't think it's fixable but I'll look into it.

**Comment by padlocks** [comment] 2022-04-28 22:24
Thank you for your time, I'll probably also create an issue with RoadRunner just incase when I get the chance to.

**Comment by zKryle** [comment] 2022-04-28 22:28
Thank you for reporting bugs, I'd never find out without you guys XD

**Comment by zKryle** [comment] 2022-04-28 23:17
I might have fixed it, I hope it was my mistake and not RoadRunner dev's XD
I'll roll the update out soon, probably tomorrow, still have to test with RoadRunner.

Gonna close this when I'm sure the bug is fixed.

**Comment by ChipsAchoy** [comment] 2022-05-12 09:18
Hi zKryle, Im running a server on aternos and Im experimenting the same problem but Im not using that road runners mod (even though Im using some other mods in my server), but when I tried in my offline world it actually worked. I want to know if u can solve it, I really loved your mod and I hope I can enjoy my big Magmatic Golem.

**Comment by zKryle** [comment] 2022-05-17 20:12
Hello everyone! I'm deeply sorry but I haven't been able to verify if the bug was fixed.
I finally did and it is, an hotfix will be released in a couple minutes and further ideas and mod developing will most likely happen in mid summer, thanks for patience!

**Closed as completed** 2022-05-17 23:06 UTC
Labels: bug, good first issue
